### ISSUE TITLE
munin-run error # Unknown service 'pisense_'

### ISSUE THREAD

**Issue by viktorsmari** [perception101/pisense#3]
When trying the plugin with `munin-run pisense_` I get the following error:
`# Unknown service 'pisense_'`

Raspberry Pi 2, raspbian jessie

**Comment by perception101** [comment]
Try
`munin-run pisense_temp`

I think you have to include the sensor you're trying to report on which is why you usually create a symbolic link from pisense_ to pisense_volt or pisense_temp, etc.

It's been a long time since i looked at the code, and even longer since I stopped running it I'm afraid!

**Comment by TafThorne** [comment]
This is a common feature of all munin plugins that use the magic _ extension.  You can set them up with configure if they support autoconfigruation but cannot run them until you have added the link.

**Comment by perception101** [comment]
Not an issue with the underlying plugin.
